name: Jest
on: push
jobs:
  test:
    defaults:
      run:
        working-directory: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "23.1.0"
      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Install required deps for action
      - name: Install Dependencies
        run: npm install
      # Start MongoDB Service
      # Install MongoDB
      - name: Install MongoDB
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
          echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
      - name: Start MongoDB
        run: sudo systemctl start mongodb
      # Start server in the background
      - name: Start Server
        run: npm start &
      # Wait for server to be ready
      - name: Wait for Server
        run: sleep 10
      # Finally, run our tests
      - name: Run the tests
        run: npm test
