name: Jest
on: push
jobs:
  test:
    defaults:
      run:
        working-directory: API
    strategy:
      matrix:
        os: [ubuntu-latest]
        mongodb-version: [latest]
        node-version: [latest]
    runs-on: ${{ matrix.os }}
    environment: tester
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "23.1.0"
      # Speed up subsequent runs with caching
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Install required deps for action
      - name: Install Dependencies
        run: npm install
      # Start server in the background
      - name: Start Server
        run: npm start &
      # Wait for server to be ready
      - name: Wait for Server
        run: sleep 3
      # Finally, run our tests
      - name: Run the tests
        run: sudo -E npm run test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
